version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/myblog
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - php
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./:/var/www/myblog
    environment:
      - XDEBUG_CONFIG=remote_host=host.docker.internal
      - PHP_IDE_CONFIG=serverName=myblog
  psql:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: blog
    ports:
      - 5432:5432
  composer:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./:/var/www/myblog
    command: bash -c "cd blog && composer install"
    depends_on:
      - php